name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

env:
  FONT_NAME: Lexend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Google Fonts
        run: |
          mkdir .cache
          wget -O fonts.zip https://fonts.google.com/download?family=$FONT_NAME
          unzip -d .cache/fonts/ fonts.zip
          
      - uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.10.0'
          
      - run: typst compile --font-path .cache/fonts/static/ --root . main.typ output.pdf
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: output.pdf
          path: output.pdf

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: output.pdf
