name: Build Typst document
on: [push, workflow_dispatch]

permissions:
  contents: write

env:
  FONT_NAME: Lexend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: 'v0.10.0'
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: EXECUTOR=local node index.mjs
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: dist/output/*

      - name: Get current date
        id: date
        run: echo "DATE=$(date +%Y-%m-%d-%H:%M)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          name: "${{ github.ref_name }} — ${{ env.DATE }}"
          files: dist/output/*
